repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: 'src/icons/.*\.svg'
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.8.0"
    hooks:
      - id: eslint
        files: \.([jt]s|astro)$ # *.js, *.ts and *.astro
        types: [file]
        additional_dependencies:
          # TODO: update ESLint to v9
          - eslint@8
          - eslint-config-prettier@9
          - eslint-plugin-unicorn@49
          - prettier@3
  - repo: https://github.com/kytta/mirrors-svgo
    rev: v4.0.0-rc.0
    hooks:
      - id: svgo
        files: "^src/icons/"
        additional_dependencies:
          - svgo@3
