name: Node.js CI

on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint and test package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
